#%RAML 1.0 DataType
 type: object
 properties:
   id:
    type: integer
    description: mention your id 
    example: 1
    required: true
   name:
    type: string
    description: name as per aadhar
    example: jayaram
    required: true
   password:
    type: string
    description: password must br min 9 letter with spl symbol and cap letter and num
    example: S@hjcjsh122
    required: true
     

    
